events {
    worker_connections 1024;
}

http {
    upstream users_service {
        server users-service:3001;
    }

    upstream products_service {
        server products-service:3002;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://users_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products {
            proxy_pass http://products_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 '{"status":"ok","gateway":"nginx"}';
            add_header Content-Type application/json;
        }
    }
}
