source "https://rubygems.org"

ruby "{{RUBY_VERSION}}"

gem "rails", "~> 7.2"
gem "sqlite3", "~> 2.0"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "debug", platforms: %i[mri windows]
end
